In [ ]:
!pip install beautifulsoup4

In [36]:
import requests
import json
from bs4 import BeautifulSoup
x = requests.get('https://s.cafef.vn/bao-cao-tai-chinh/VCB/IncSta/2023/0/0/0/0/ket-qua-hoat-dong-kinh-doanh-ngan-hang-thuong-mai-co-phan-ngoai-thuong-viet-nam.chn')

htmldiv = BeautifulSoup(x.content)

tableData = htmldiv.find("table", {"id": "tableContent"})

cellHeaders = htmldiv.find("table", {"id": "tblGridData"}).find("tr").find_all("td")[1:5]
jsonTitle = []
jsonTitle.append("VCB_KetQuaHoatDongKinhDoanh_Theo_Nam")
jsonHeader = []
for cellHeader in cellHeaders:
  jsonHeader.append(cellHeader.text.strip())

linesTable = tableData.find_all("tr")

jsonData = []

for lineTable in linesTable:
  cellTables = lineTable.find_all("td", limit=5)
  jsonData_line = []
  for cellTable in cellTables:
    jsonData_line.append(cellTable.text.strip())
  jsonData.append(jsonData_line)

jsonData.insert(0, [ *jsonTitle])
jsonData.insert(1, ["", *jsonHeader])

f = open("data.json", "w")
f.write(json.dumps(jsonData))
f.close()

f = open("data.json", "r")
jsonDataReaded = f.read()

jsonDataFormated = json.loads(jsonDataReaded)
formatted_data = [row for row in jsonDataFormated if any(row)]
formatted_data

# import pandas as pd
# df = pd.DataFrame(formatted_data)
# df

[['VCB_KetQuaHoatDongKinhDoanh_Theo_Nam'],
 ['', '2019', '2020', '2021', '2022'],
 ['Thu nhập lãi ròng',
  '34,577,350,000,000',
  '36,285,475,000,000',
  '42,399,617,000,000',
  '53,246,478,000,000'],
 ['Thu nhập lãi và các khoản thu nhập tương tự',
  '67,724,190,000,000',
  '69,205,134,000,000',
  '70,749,002,000,000',
  '88,112,700,000,000'],
 ['Chi phí lãi và các khoản chi phí tương tự',
  '33,146,840,000,000',
  '32,919,659,000,000',
  '28,349,385,000,000',
  '34,866,222,000,000'],
 ['Lãi/lỗ ròng từ hoạt động dịch vụ',
  '4,306,844,000,000',
  '6,607,317,000,000',
  '7,407,073,000,000',
  '6,839,100,000,000'],
 ['Thu nhập từ hoạt động dịch vụ',
  '9,002,507,000,000',
  '10,588,163,000,000',
  '11,286,516,000,000',
  '12,425,007,000,000'],
 ['Chi phí hoạt động dịch vụ',
  '4,695,663,000,000',
  '3,980,846,000,000',
  '3,879,443,000,000',
  '5,585,907,000,000'],
 ['Lãi/lỗ ròng từ hoạt động kinh doanh ngoại hối và vàng',
  '3,378,274,000,000',
  '3,906,399,000,000',
  '4,374,820,000,000',
  '5,768,445,000,000'],
 ['Lãi/lỗ thuần từ mua bán chứng khoán kinh doanh',
  '145,982,000,000',
  '1,810,000,000',
  '104,114,000,000',
  '-115,194,000,000'],
 ['Lãi/ lỗ thuần từ mua bán chứng khoán đầu tư',
  '7,040,000,000',
  '-98,000,000',
  '-85,126,000,000',
  '81,595,000,000'],
 ['Lãi thuần từ hoạt động khác',
  '3,069,795,000,000',
  '1,800,253,000,000',
  '2,393,261,000,000',
  '2,053,961,000,000'],
 ['Thu nhập hoạt động khác',
  '3,427,765,000,000',
  '2,544,714,000,000',
  '3,100,370,000,000',
  '2,928,339,000,000'],
 ['Chi phí hoạt động khác',
  '357,970,000,000',
  '744,461,000,000',
  '707,109,000,000',
  '874,378,000,000'],
 ['Thu nhập từ góp vốn, mua cổ phần',
  '245,096,000,000',
  '461,385,000,000',
  '129,810,000,000',
  '208,436,000,000'],
 ['Tổng thu nhập kinh doanh',
  '45,730,381,000,000',
  '49,062,541,000,000',
  '56,723,569,000,000',
  '68,082,821,000,000'],
 ['Lãi/ lỗ trong công ty liên kết, liên doanh', '', '', '', ''],
 ['Chi phí hoạt động',
  '15,817,575,000,000',
  '16,038,250,000,000',
  '17,574,188,000,000',
  '21,250,512,000,000'],
 ['Chi phí nhân viên', '', '', '', ''],
 ['Chi phí khấu hao', '', '', '', ''],
 ['Chi phí hoạt động khác', '', '', '', ''],
 ['Lợi nhuận ròng từ hoạt động kinh doanh trước chi phí dự phòng',
  '29,912,806,000,000',
  '33,024,291,000,000',
  '39,149,381,000,000',
  '46,832,309,000,000'],
 ['Chi phí dự phòng', '', '', '', ''],
 ['Chi phí dự phòng rủi ro tín dụng',
  '6,790,429,000,000',
  '9,974,730,000,000',
  '11,760,801,000,000',
  '9,464,218,000,000'],
 ['Các khoản xử lý theo đề tài cấu trúc Ngân hàng', '', '', '', ''],
 ['Dự phòng chung cho các khoản cam kết và nợ tiềm tàng', '', '', '', ''],
 ['Dự phòng giảm giá chứng khoán', '', '', '', ''],
 ['Thu hồi nợ đã xử lý bằng nguồn dự phòng', '', '', '', ''],
 ['Tổng lợi nhuận kế toán',
  '23,122,377,000,000',
  '23,049,561,000,000',
  '27,388,580,000,000',
  '37,368,091,000,000'],
 ['Thu nhập từ các khoản nợ khó đòi', '', '', '', ''],
 ['Lợi nhuận được hưởng từ các công ty liên kết và liên doanh',
  '',
  '',
  '',
  ''],
 ['Tổng lợi nhuận trước thuế',
  '23,122,377,000,000',
  '23,049,561,000,000',
  '27,388,580,000,000',
  '37,368,091,000,000'],
 ['Chi phí thuế TNDN',
  '4,992,464,000,000',
  '5,081,068,000,000',
  '4,547,363,000,000',
  '8,406,860,000,000'],
 ['Chi phí thuế hiện hành', '', '', '', ''],
 ['Chi phí thuế hoãn lại',
  '-396,075,000,000',
  '-504,025,000,000',
  '902,172,000,000',
  '-957,823,000,000'],
 ['Lợi nhuận sau thuế',
  '18,525,988,000,000',
  '18,472,518,000,000',
  '21,939,045,000,000',
  '29,919,054,000,000'],
 ['Lợi ích của cổ đông thiểu số',
  '15,090,000,000',
  '21,207,000,000',
  '20,232,000,000',
  '20,040,000,000'],
 ['Lợi nhuận sau thuế của cổ đông công ty mẹ',
  '18,510,898,000,000',
  '18,451,311,000,000',
  '21,918,813,000,000',
  '29,899,014,000,000'],
 ['Lãi cơ bản trên cổ phiếu', '4,481', '4,470', '4,195', '5,821'],
 ['Lãi suy giảm trên cổ phiếu', '', '', '', '']]

In [34]:
import pandas as pd

In [37]:
df = pd.DataFrame(formatted_data)
df.head(20)

,0,1,2,3,4
0,VCB_KetQuaHoatDongKinhDoanh_Theo_Nam,None,None,None,None
1,,2019,2020,2021,2022
2,Thu nhập lãi ròng,"34,577,350,000,000","36,285,475,000,000","42,399,617,000,000","53,246,478,000,000"
3,Thu nhập lãi và các khoản thu nhập tương tự,"67,724,190,000,000","69,205,134,000,000","70,749,002,000,000","88,112,700,000,000"
4,Chi phí lãi và các khoản chi phí tương tự,"33,146,840,000,000","32,919,659,000,000","28,349,385,000,000","34,866,222,000,000"
5,Lãi/lỗ ròng từ hoạt động dịch vụ,"4,306,844,000,000","6,607,317,000,000","7,407,073,000,000","6,839,100,000,000"
6,Thu nhập từ hoạt động dịch vụ,"9,002,507,000,000","10,588,163,000,000","11,286,516,000,000","12,425,007,000,000"
7,Chi phí hoạt động dịch vụ,"4,695,663,000,000","3,980,846,000,000","3,879,443,000,000","5,585,907,000,000"
8,Lãi/lỗ ròng từ hoạt động kinh doanh ngoại hối ...,"3,378,274,000,000","3,906,399,000,000","4,374,820,000,000","5,768,445,000,000"
9,Lãi/lỗ thuần từ mua bán chứng khoán kinh doanh,"145,982,000,000","1,810,000,000","104,114,000,000","-115,194,000,000"
10,Lãi/ lỗ thuần từ mua bán chứng khoán đầu tư,"7,040,000,000","-98,000,000","-85,126,000,000","81,595,000,000"
11,Lãi thuần từ hoạt động khác,"3,069,795,000,000","1,800,253,000,000","2,393,261,000,000","2,053,961,000,000"
12,Thu nhập hoạt động khác,"3,427,765,000,000","2,544,714,000,000","3,100,370,000,000","2,928,339,000,000"
13,Chi phí hoạt động khác,"357,970,000,000","744,461,000,000","707,109,000,000","874,378,000,000"
14,"Thu nhập từ góp vốn, mua cổ phần","245,096,000,000","461,385,000,000","129,810,000,000","208,436,000,000"
15,Tổng thu nhập kinh doanh,"45,730,381,000,000","49,062,541,000,000","56,723,569,000,000","68,082,821,000,000"
16,"Lãi/ lỗ trong công ty liên kết, liên doanh",,,,
17,Chi phí hoạt động,"15,817,575,000,000","16,038,250,000,000","17,574,188,000,000","21,250,512,000,000"
18,Chi phí nhân viên,,,,
19,Chi phí khấu hao,,,,